# -*- coding: utf-8 -*-
"""Generate and catalog local TurbSim and FAST.Farm primary inputs."""
from __future__ import annotations

import hashlib
import pathlib
import re
from typing import Any


ROOT = pathlib.Path(__file__).resolve().parents[1]
TOOL_INPUTS = ROOT / "tool_inputs"
SAFE_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def _quoted(value: Any) -> str:
    return '"' + str(value).replace("\\", "/").replace('"', '') + '"'


def turbsim_input_text(spec: dict[str, Any]) -> str:
    seed = int(spec.get("seed", 10101))
    wind_speed = float(spec.get("wind_speed", 8.0))
    analysis_time = float(spec.get("analysis_time", 720.0))
    timestep = float(spec.get("timestep", 0.05))
    hub_height = float(spec.get("hub_height", 150.0))
    grid_height = float(spec.get("grid_height", 252.0))
    grid_width = float(spec.get("grid_width", 252.0))
    iec_class = str(spec.get("iec_turbulence_class", "B"))
    wind_model = str(spec.get("wind_model", "NTM")).upper()
    return f"""---------TurbSim v2.00.* Input File------------------------
Generated by openfast-gui.
---------Runtime Options-----------------------------------
False         Echo
{seed}        RandSeed1
"RANLUX"      RandSeed2
False         WrBHHTP
False         WrFHHTP
False         WrADHH
True          WrADFF
False         WrBLFF
False         WrADTWR
False         WrFMTFF
False         WrACT
True          Clockwise
0             ScaleIEC
--------Turbine/Model Specifications-----------------------
21            NumGrid_Z
21            NumGrid_Y
{timestep:g}  TimeStep
{analysis_time:g} AnalysisTime
"ALL"         UsableTime
{hub_height:g} HubHt
{grid_height:g} GridHeight
{grid_width:g} GridWidth
0.0           VFlowAng
0.0           HFlowAng
--------Meteorological Boundary Conditions-------------------
"IECKAI"      TurbModel
"unused"      UserFile
"1-ED3"       IECstandard
{iec_class}             IECturbc
{wind_model}           IEC_WindType
"default"     ETMc
"PL"          WindProfileType
"unused"      ProfileFile
{hub_height:g} RefHt
{wind_speed:g} URef
"default"     ZJetMax
0.11          PLExp
"default"     Z0
--------Non-IEC Meteorological Boundary Conditions------------
"default"     Latitude
0.05          RICH_NO
"default"     UStar
"default"     ZI
"default"     PC_UW
"default"     PC_UV
"default"     PC_VW
--------Spatial Coherence Parameters----------------------------
"GENERAL"     SCMod1
"GENERAL"     SCMod2
"GENERAL"     SCMod3
"13.750000 0.040000"  InCDec1
"9.850000 0.001500"   InCDec2
"9.500000 0.003000"   InCDec3
0.5           CohExp
--------Coherent Turbulence Scaling Parameters-------------------
"unused"      CTEventPath
"Random"      CTEventFile
True          Randomize
1             DistScl
0.5           CTLy
0.5           CTLz
30            CTStartTime
====================================================
"""


def fastfarm_input_text(spec: dict[str, Any]) -> str:
    tmax = float(spec.get("tmax", 600.0))
    fst_file = _quoted(spec.get("fst_file", "OpenFAST.fst"))
    inflow_file = _quoted(spec.get("inflow_file", "InflowWind.dat"))
    turbines = max(1, min(int(spec.get("turbines", 1)), 50))
    spacing = float(spec.get("spacing", 1680.0))
    hub_height = float(spec.get("hub_height", 150.0))
    rotor_diameter = float(spec.get("rotor_diameter", 240.0))
    dx = float(spec.get("grid_spacing", max(5.0, rotor_diameter / 20.0)))
    turbine_rows = []
    for index in range(turbines):
        x = index * spacing
        y = 0.0
        x0 = x - rotor_diameter * 0.75
        y0 = y - rotor_diameter * 0.75
        z0 = max(0.0, hub_height - rotor_diameter * 0.75)
        turbine_rows.append(f"{x:.3f}  {y:.3f}  0.0  {fst_file}  {x0:.3f}  {y0:.3f}  {z0:.3f}  {dx:.3f}  {dx:.3f}  {dx:.3f}")
    return f"""------- FAST.Farm for OpenFAST INPUT FILE -------------------------------
Generated by openfast-gui; review grid extents before production runs.
--- SIMULATION CONTROL ---
False         Echo                  - Echo input data
FATAL         AbortLevel            - Abort level
{tmax:g}      TMax                  - Total run time (s)
2             Mod_AmbWind           - One InflowWind instance
2             Mod_WaveField         - Adjust wave phases by turbine position
0             Mod_SharedMooring     - No shared mooring
--- SHARED MOORING SYSTEM ---
""            SharedMoorFile
0.04          DT_Mooring
--- AMBIENT WIND: PRECURSOR IN VTK FORMAT ---
2.0           DT_Low-VTK
0.5           DT_High-VTK
"unused"      WindFilePath
False         ChkWndFiles
--- AMBIENT WIND: INFLOWWIND MODULE ---
2.0           DT_Low
0.5           DT_High
300           NX_Low
300           NY_Low
35            NZ_Low
-500.0        X0_Low
-500.0        Y0_Low
0.0           Z0_Low
10.0          dX_Low
10.0          dY_Low
10.0          dZ_Low
31            NX_High
31            NY_High
31            NZ_High
{inflow_file} InflowFile
--- WIND TURBINES ---
{turbines}     NumTurbines
WT_X WT_Y WT_Z WT_FASTInFile X0_High Y0_High Z0_High dX_High dY_High dZ_High
(m) (m) (m) (string) (m) (m) (m) (m) (m) (m)
{chr(10).join(turbine_rows)}
--- WAKE DYNAMICS ---
1             Mod_Wake
5.0           dr
40            NumRadii
140           NumPlanes
DEFAULT       f_c
DEFAULT       C_HWkDfl_O
DEFAULT       C_HWkDfl_OY
DEFAULT       C_HWkDfl_x
DEFAULT       C_HWkDfl_xY
DEFAULT       C_NearWake
DEFAULT       k_vAmb
DEFAULT       k_vShr
DEFAULT       C_vAmb_DMin
DEFAULT       C_vAmb_DMax
DEFAULT       C_vAmb_FMin
DEFAULT       C_vAmb_Exp
DEFAULT       C_vShr_DMin
DEFAULT       C_vShr_DMax
DEFAULT       C_vShr_FMin
DEFAULT       C_vShr_Exp
DEFAULT       Mod_WakeDiam
DEFAULT       C_WakeDiam
DEFAULT       Mod_Meander
DEFAULT       C_Meander
--- CURLED-WAKE PARAMETERS ---
True          Swirl
0             k_VortexDecay
DEFAULT       NumVortices
DEFAULT       sigma_D
DEFAULT       FilterInit
DEFAULT       k_vCurl
DEFAULT       Mod_Projection
--- VISUALIZATION ---
False         WrDisWind
0             NOutDisWindXY
0.0           OutDisWindZ
0             NOutDisWindYZ
0.0           OutDisWindX
0             NOutDisWindXZ
0.0           OutDisWindY
4.0           WrDisDT
--- OUTPUT ---
True          SumPrint
99999.9       ChkptTime
0.0           TStart
1             OutFileFmt
True          TabDelim
"ES10.3E2"    OutFmt
False         OutAllPlanes
3             NOutRadii
0,15,39       OutRadii
2             NOutDist
0.0,378.0     OutDist
1             NWindVel
0.0           WindVelX
0.0           WindVelY
{hub_height:g} WindVelZ
OutList
"RtAxsXT1, RtAxsYT1, RtAxsZT1"
"RtPosXT1, RtPosYT1, RtPosZT1"
"YawErrT1, TIAmbT1"
END
"""


def safe_tool_input_path(filename: str) -> pathlib.Path:
    name = pathlib.Path(str(filename)).name
    if not name or not SAFE_NAME_RE.fullmatch(name):
        raise ValueError("Tool input filename may contain only letters, numbers, dot, dash and underscore")
    path = (TOOL_INPUTS / name).resolve()
    path.relative_to(TOOL_INPUTS.resolve())
    return path


def generate_tool_input(kind: str, filename: str, spec: dict[str, Any]) -> dict[str, Any]:
    kind = str(kind).lower()
    if kind == "turbsim":
        if not filename.lower().endswith(".in"):
            filename += ".in"
        content = turbsim_input_text(spec)
    elif kind == "fastfarm":
        if not filename.lower().endswith(".fstf"):
            filename += ".fstf"
        content = fastfarm_input_text(spec)
    else:
        raise ValueError(f"Unsupported tool input kind: {kind}")
    TOOL_INPUTS.mkdir(parents=True, exist_ok=True)
    path = safe_tool_input_path(filename)
    path.write_text(content, encoding="utf-8")
    return {"kind": kind, "file": path.name, "path": str(path), "size": path.stat().st_size}


def tool_input_catalog() -> list[dict[str, Any]]:
    TOOL_INPUTS.mkdir(parents=True, exist_ok=True)
    rows = []
    for path in TOOL_INPUTS.iterdir():
        if not path.is_file() or path.name == "README.md":
            continue
        kind = "fastfarm" if path.suffix.lower() == ".fstf" else "turbsim" if path.suffix.lower() == ".in" else "generic"
        rows.append({"file": path.name, "kind": kind, "size": path.stat().st_size, "modified": path.stat().st_mtime})
    return sorted(rows, key=lambda row: row["file"].lower())


def save_tool_input(filename: str, content: str, source_sha256: str = "") -> dict[str, Any]:
    path = safe_tool_input_path(filename)
    if not path.is_file():
        raise FileNotFoundError(f"Tool input not found: {filename}")
    before = hashlib.sha256(path.read_bytes()).hexdigest()
    if source_sha256 and source_sha256 != before:
        raise ValueError("Tool input changed after it was opened; reload before saving")
    if len(content.encode("utf-8")) > 4 * 1024 * 1024:
        raise ValueError("Tool input exceeds the 4 MiB editor limit")
    path.write_text(content, encoding="utf-8", newline="")
    return {
        "file": path.name,
        "path": str(path),
        "before_sha256": before,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "size": path.stat().st_size,
    }
